version: "3"

services:
    www:
        build: .
        restart: always
        ports:
            - '8000:80'
        volumes:
            - ./www:/var/www/html
        networks:
            - default
    db:
        image: mysql:9.1.0
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: meudb
            MYSQL_USER: alan
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: abcdef
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - default

volumes:
    db_data:
